### ISSUE TITLE
NCD Firmware Downgrade from ver.6 to currently using ver.5

### ISSUE THREAD

**Issue by MTS-Chris** [bhaskar-anil429/MT#1]
Hi Bhaskar,
Good morning,
Please advise on the attached error messages during Firmware patch loading ver5...Unexpected error occurred when executing...thanks

![image](https://github.com/bhaskar-anil429/MT/assets/173761845/00a5ed46-d21f-4b1c-ae80-ba6a5c4579c8)
![image](https://github.com/bhaskar-anil429/MT/assets/173761845/7dc232cf-fe70-4ae9-9d66-5f167dcacf8a)

**Comment by bhaskar-anil429** [comment]
Make sure the programmer's direction is correct. you can try by flipping it around.

**Comment by MTS-Chris** [comment]
Hi Bhaskar,
you mean is flipping the connector on another side...I have already done it also. please see error below
![image](https://github.com/bhaskar-anil429/MT/assets/173761845/5b5cf6dc-fb64-4f5f-a7b6-f0e1abd45f05)
